#!/usr/bin/env python3
"""CLI entry point for dictation-reviewer.

Loads pre-generated corrections JSON and produces an interactive HTML review page.
Note fetching and correction generation are handled by note-manager.
"""

import argparse
import json
import sys
import webbrowser
from pathlib import Path

from config import DEFAULT_OUTPUT_DIR, default_output_filename
from template import build_html


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Dictation Reviewer — build HTML review page from corrections JSON",
    )
    parser.add_argument(
        "--corrections-file", "-c",
        required=True,
        help="Path to corrections JSON file (generated by note-manager)",
    )
    parser.add_argument(
        "--output", "-o",
        help="Output HTML path (default: YYYYMMDD_HHMM_review.html)",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory to save the HTML file",
    )
    parser.add_argument(
        "--title",
        default="Dictation Review",
        help="Custom title for the review page",
    )
    parser.add_argument(
        "--auto-open",
        action="store_true",
        help="Open HTML in browser after generation",
    )
    return parser.parse_args()


def load_corrections(path: str) -> list[dict]:
    p = Path(path)
    if not p.exists():
        print(f"Error: corrections file not found: {path}", file=sys.stderr)
        sys.exit(1)
    corrections = json.loads(p.read_text(encoding="utf-8"))
    print(f"Loaded {len(corrections)} corrections.")
    return corrections


def main() -> None:
    args = parse_args()

    corrections = load_corrections(args.corrections_file)

    html_content = build_html(corrections, title=args.title)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / (args.output or default_output_filename("html"))
    output_path.write_text(html_content, encoding="utf-8")
    print(f"Review page saved to: {output_path}")

    if args.auto_open:
        webbrowser.open(f"file://{output_path.resolve()}")


if __name__ == "__main__":
    main()
